
DROP TABLE IF EXISTS CORP_FUNC_MST;
CREATE TABLE CORP_FUNC_MST (
  CORP_CODE varchar(35) NOT NULL,
  FUNC_CODE varchar(2) NOT NULL,
  EXEC_FREQ char(1) NOT NULL,
  DAY_OF_WEEK varchar(7) NOT NULL,
  DAY_OF_MONTH varchar(28) NOT NULL,
  VIP_FLAG char(1) NOT NULL,
  OVERNIGHT_FLAG char(1) NOT NULL,
  EFFECTIVE_DATE date NOT NULL,
  ACTIVE_STATUS char(1) NOT NULL,
  AUTHORIZE_STATUS char(1) NOT NULL,
  REJECT_REASON varchar(255) DEFAULT NULL,
  OPERATION_FLAG char(1) NOT NULL,
  SYNC_DATE datetime DEFAULT NULL,
  SYNC_STATUS char(1) DEFAULT NULL,
  SYNC_MESSAGE varchar(255) DEFAULT NULL,
  CREATED_DATE datetime NOT NULL,
  CREATED_BY varchar(20) NOT NULL,
  AUTHORIZED_DATE datetime DEFAULT NULL,
  AUTHORIZED_BY varchar(20) DEFAULT NULL,
  LAST_UPDATED_DATE datetime NOT NULL,
  LAST_UPDATED_BY varchar(20) NOT NULL,
  PRIMARY KEY (CORP_CODE),
);

