
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.kasikornbank.eai.eaiws.cbs1183i01.v2;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2560-05-08T17:24:21.102+07:00
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "CBS1183I01",
                      portName = "CBS1183I01SoapPort",
                      targetNamespace = "http://eai.kasikornbank.com/EAIWS/CBS1183I01/v2",
                      wsdlLocation = "classpath:xsd/CBS1183I01.wsdl",
                      endpointInterface = "com.kasikornbank.eai.eaiws.cbs1183i01.v2.CBS1183I01Soap")
                      
public class CBS1183I01SoapPortImpl implements CBS1183I01Soap {

    private static final Logger LOG = Logger.getLogger(CBS1183I01SoapPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.kasikornbank.eai.eaiws.cbs1183i01.v2.CBS1183I01Soap#doService(com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoService.CBS1183I01 cbs1183I01)*
     */
    
    public com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoServiceResponse.CBS1183I01Response doService(com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoService.CBS1183I01 cbs1183I01)  { 
        LOG.info("Executing operation doService");
        
        com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoServiceResponse.CBS1183I01Response _return = new com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoServiceResponse.CBS1183I01Response();
        try {
	        com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoServiceResponse.CBS1183I01Response.KBankHeader _returnKBankHeader = new com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoServiceResponse.CBS1183I01Response.KBankHeader();
	        _returnKBankHeader.setFuncNm("FuncNm631178162");
	        _returnKBankHeader.setRqUID("RqUID-1261772903");
	        _returnKBankHeader.setRsAppId("RsAppId763780065");
	        _returnKBankHeader.setRsUID("RsUID-257694126");
	        _returnKBankHeader.setRsDt(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-05-08T17:24:21.113+07:00"));
	        _returnKBankHeader.setStatusCode("StatusCode-490791206");
	        com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoServiceResponse.CBS1183I01Response.KBankHeader.ErrorVect _returnKBankHeaderErrorVect = new com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoServiceResponse.CBS1183I01Response.KBankHeader.ErrorVect();
	        java.util.List<com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoServiceResponse.CBS1183I01Response.KBankHeader.ErrorVect.Error> _returnKBankHeaderErrorVectError = new java.util.ArrayList<com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoServiceResponse.CBS1183I01Response.KBankHeader.ErrorVect.Error>();
	        _returnKBankHeaderErrorVect.getError().addAll(_returnKBankHeaderErrorVectError);
	        _returnKBankHeader.setErrorVect(_returnKBankHeaderErrorVect);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnKBankHeaderCorrID = null;
	        _returnKBankHeader.setCorrID(_returnKBankHeaderCorrID);
	        _return.setKBankHeader(_returnKBankHeader);
	        com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoServiceResponse.CBS1183I01Response.CBSAccount _returnCBSAccount = new com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoServiceResponse.CBS1183I01Response.CBSAccount();
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountAccrueIntAmt = null;
	        _returnCBSAccount.setAccrueIntAmt(_returnCBSAccountAccrueIntAmt);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountAcctBal = null;
	        _returnCBSAccount.setAcctBal(_returnCBSAccountAcctBal);
	        _returnCBSAccount.setAcctId("AcctId2113330814");
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCBSAccountAcctNameEn = null;
	        _returnCBSAccount.setAcctNameEn(_returnCBSAccountAcctNameEn);
	        _returnCBSAccount.setAcctNameTh("AcctNameTh245416684");
	        _returnCBSAccount.setAcctStatus("AcctStatus378494062");
	        _returnCBSAccount.setAcctStatusDesc("AcctStatusDesc1016848546");
	        _returnCBSAccount.setAllowFlag("AllowFlag375099482");
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountApparentPassbkBal = null;
	        _returnCBSAccount.setApparentPassbkBal(_returnCBSAccountApparentPassbkBal);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountAvailBal = null;
	        _returnCBSAccount.setAvailBal(_returnCBSAccountAvailBal);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountAvailENCLimitAmt = null;
	        _returnCBSAccount.setAvailENCLimitAmt(_returnCBSAccountAvailENCLimitAmt);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountAvailIntradayLimitAmt = null;
	        _returnCBSAccount.setAvailIntradayLimitAmt(_returnCBSAccountAvailIntradayLimitAmt);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountAvailLimitAmt = null;
	        _returnCBSAccount.setAvailLimitAmt(_returnCBSAccountAvailLimitAmt);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountAvailODLimitAmt = null;
	        _returnCBSAccount.setAvailODLimitAmt(_returnCBSAccountAvailODLimitAmt);
	        _returnCBSAccount.setBlockInd("BlockInd-579870444");
	        _returnCBSAccount.setBranchName("BranchName230564285");
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountClearingAmt = null;
	        _returnCBSAccount.setClearingAmt(_returnCBSAccountClearingAmt);
	        javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnCBSAccountClosedDt = null;
	        _returnCBSAccount.setClosedDt(_returnCBSAccountClosedDt);
	        _returnCBSAccount.setCurcode("Curcode-52772234");
	        _returnCBSAccount.setDomicileBranchId("DomicileBranchId1281275635");
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountENCLimitAmt = null;
	        _returnCBSAccount.setENCLimitAmt(_returnCBSAccountENCLimitAmt);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountENCLimitUsed = null;
	        _returnCBSAccount.setENCLimitUsed(_returnCBSAccountENCLimitUsed);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountHoldAmt = null;
	        _returnCBSAccount.setHoldAmt(_returnCBSAccountHoldAmt);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountIntradayLimitAmt = null;
	        _returnCBSAccount.setIntradayLimitAmt(_returnCBSAccountIntradayLimitAmt);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountIntradayLimitUsed = null;
	        _returnCBSAccount.setIntradayLimitUsed(_returnCBSAccountIntradayLimitUsed);
	        _returnCBSAccount.setKBankProductCode("KBankProductCode966407170");
	        _returnCBSAccount.setKBankProductCodeDesc("KBankProductCodeDesc1753863975");
	        javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _returnCBSAccountLastFincDt = null;
	        _returnCBSAccount.setLastFincDt(_returnCBSAccountLastFincDt);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountLimitAmt = null;
	        _returnCBSAccount.setLimitAmt(_returnCBSAccountLimitAmt);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountLimitUsed = null;
	        _returnCBSAccount.setLimitUsed(_returnCBSAccountLimitUsed);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountODLimitAmt = null;
	        _returnCBSAccount.setODLimitAmt(_returnCBSAccountODLimitAmt);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountODLimitUsed = null;
	        _returnCBSAccount.setODLimitUsed(_returnCBSAccountODLimitUsed);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountRefAcctBal = null;
	        _returnCBSAccount.setRefAcctBal(_returnCBSAccountRefAcctBal);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCBSAccountRefAcctId = null;
	        _returnCBSAccount.setRefAcctId(_returnCBSAccountRefAcctId);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCBSAccountRefBranchId = null;
	        _returnCBSAccount.setRefBranchId(_returnCBSAccountRefBranchId);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCBSAccountRefBranchName = null;
	        _returnCBSAccount.setRefBranchName(_returnCBSAccountRefBranchName);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCBSAccountRefProductCode = null;
	        _returnCBSAccount.setRefProductCode(_returnCBSAccountRefProductCode);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCBSAccountRefProductDesc = null;
	        _returnCBSAccount.setRefProductDesc(_returnCBSAccountRefProductDesc);
	        javax.xml.bind.JAXBElement<java.math.BigDecimal> _returnCBSAccountRetentionAmt = null;
	        _returnCBSAccount.setRetentionAmt(_returnCBSAccountRetentionAmt);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCBSAccountTCBTariffName = null;
	        _returnCBSAccount.setTCBTariffName(_returnCBSAccountTCBTariffName);
	        _return.setCBSAccount(_returnCBSAccount);
        } catch(Exception e){
        	LOG.info(e.getMessage());
        }
        return _return;
    }

}
