package com.kasikornbank.eai.eaiws.cbs1183i01.v2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2560-05-08T17:24:21.117+07:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://eai.kasikornbank.com/EAIWS/CBS1183I01/v2", name = "CBS1183I01Soap")
@XmlSeeAlso({ObjectFactory.class})
@FunctionalInterface
public interface CBS1183I01Soap {

    @WebMethod
    @RequestWrapper(localName = "doService", targetNamespace = "http://eai.kasikornbank.com/EAIWS/CBS1183I01/v2", className = "com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoService")
    @ResponseWrapper(localName = "doServiceResponse", targetNamespace = "http://eai.kasikornbank.com/EAIWS/CBS1183I01/v2", className = "com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoServiceResponse")
    @WebResult(name = "CBS1183I01Response", targetNamespace = "http://eai.kasikornbank.com/EAIWS/CBS1183I01/v2")
    public com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoServiceResponse.CBS1183I01Response doService(
        @WebParam(name = "CBS1183I01", targetNamespace = "http://eai.kasikornbank.com/EAIWS/CBS1183I01/v2")
        com.kasikornbank.eai.eaiws.cbs1183i01.v2.DoService.CBS1183I01 cbs1183I01
    );
}
