package com.kasikornbank.eai.eaiws.cbs1183i01.v2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2560-05-08T17:24:21.124+07:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "CBS1183I01", 
                  wsdlLocation = "classpath:xsd/CBS1183I01.wsdl",
                  targetNamespace = "http://eai.kasikornbank.com/EAIWS/CBS1183I01/v2") 
public class CBS1183I01 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://eai.kasikornbank.com/EAIWS/CBS1183I01/v2", "CBS1183I01");
    public final static QName CBS1183I01SoapPort = new QName("http://eai.kasikornbank.com/EAIWS/CBS1183I01/v2", "CBS1183I01SoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/LMS/LMSMasterSetup/src/main/resources/xsd/CBS1183I01.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CBS1183I01.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/xsd/CBS1183I01.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CBS1183I01(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CBS1183I01(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CBS1183I01() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CBS1183I01(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CBS1183I01(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CBS1183I01(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CBS1183I01Soap
     */
    @WebEndpoint(name = "CBS1183I01SoapPort")
    public CBS1183I01Soap getCBS1183I01SoapPort() {
        return super.getPort(CBS1183I01SoapPort, CBS1183I01Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CBS1183I01Soap
     */
    @WebEndpoint(name = "CBS1183I01SoapPort")
    public CBS1183I01Soap getCBS1183I01SoapPort(WebServiceFeature... features) {
        return super.getPort(CBS1183I01SoapPort, CBS1183I01Soap.class, features);
    }

}
