
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.kasikornbank.eai.eaiws.kbank1554i01.v1;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-16T10:46:01.961+07:00
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "KBANK1554I01",
                      portName = "KBANK1554I01SoapPort",
                      targetNamespace = "http://eai.kasikornbank.com/EAIWS/KBANK1554I01/v1",
                      wsdlLocation = "classpath:xsd/KBANK1554I01.wsdl",
                      endpointInterface = "com.kasikornbank.eai.eaiws.kbank1554i01.v1.KBANK1554I01Soap")
                      
public class KBANK1554I01SoapPortImpl implements KBANK1554I01Soap {

    private static final Logger LOG = Logger.getLogger(KBANK1554I01SoapPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.kasikornbank.eai.eaiws.kbank1554i01.v1.KBANK1554I01Soap#doService(com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoService.KBANK1554I01 kbank1554I01)*
     */
    
    public com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response doService(com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoService.KBANK1554I01 kbank1554I01) { 
        LOG.info("Executing operation doService");
        com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response _return = new com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response();
        try {
	        com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response.KBankHeader _returnKBankHeader = new com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response.KBankHeader();
	        _returnKBankHeader.setFuncNm("FuncNm-2125781399");
	        _returnKBankHeader.setRqUID("RqUID1668994242");
	        _returnKBankHeader.setRsAppId("RsAppId2120456798");
	        _returnKBankHeader.setRsUID("RsUID-928168297");
	        _returnKBankHeader.setRsDt(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-05-16T10:46:01.977+07:00"));
	        _returnKBankHeader.setStatusCode("StatusCode-796791795");
	        com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response.KBankHeader.ErrorVect _returnKBankHeaderErrorVect = new com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response.KBankHeader.ErrorVect();
	        java.util.List<com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response.KBankHeader.ErrorVect.Error> _returnKBankHeaderErrorVectError = new java.util.ArrayList<com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response.KBankHeader.ErrorVect.Error>();
	        _returnKBankHeaderErrorVect.getError().addAll(_returnKBankHeaderErrorVectError);
	        _returnKBankHeader.setErrorVect(_returnKBankHeaderErrorVect);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnKBankHeaderCorrID = null;
	        _returnKBankHeader.setCorrID(_returnKBankHeaderCorrID);
	        javax.xml.bind.JAXBElement<java.lang.Integer> _returnKBankHeaderReqAuthLevel = null;
	        _returnKBankHeader.setReqAuthLevel(_returnKBankHeaderReqAuthLevel);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnKBankHeaderReqAuthUserId = null;
	        _returnKBankHeader.setReqAuthUserId(_returnKBankHeaderReqAuthUserId);
	        _return.setKBankHeader(_returnKBankHeader);
	        com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response.CVRSInfo _returnCVRSInfo = new com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response.CVRSInfo();
	        com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response.CVRSInfo.RegulsObj _returnCVRSInfoRegulsObj = new com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response.CVRSInfo.RegulsObj();
	        com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response.CVRSInfo.RegulsObj.RegulsVect _returnCVRSInfoRegulsObjRegulsVect = new com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response.CVRSInfo.RegulsObj.RegulsVect();
	        java.util.List<com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response.CVRSInfo.RegulsObj.RegulsVect.CVRSRegulation> _returnCVRSInfoRegulsObjRegulsVectCVRSRegulation = new java.util.ArrayList<com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response.CVRSInfo.RegulsObj.RegulsVect.CVRSRegulation>();
	        _returnCVRSInfoRegulsObjRegulsVect.getCVRSRegulation().addAll(_returnCVRSInfoRegulsObjRegulsVectCVRSRegulation);
	        _returnCVRSInfoRegulsObj.setRegulsVect(_returnCVRSInfoRegulsObjRegulsVect);
	        _returnCVRSInfoRegulsObj.setTotRegulCnt(Integer.valueOf(-1711597269));
	        _returnCVRSInfo.setRegulsObj(_returnCVRSInfoRegulsObj);
	        _returnCVRSInfo.setSanctionFlg("SanctionFlg1191393423");
	        _return.setCVRSInfo(_returnCVRSInfo);
        } catch(Exception e){
        	LOG.info(e.getMessage());
        }
        return _return;
    }

}
