
package com.kasikornbank.eai.eaiws.kbank1554i01.v1;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-16T10:46:01.915+07:00
 * Generated source version: 3.1.11
 * 
 */
public final class KBANK1554I01Soap_KBANK1554I01SoapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://eai.kasikornbank.com/EAIWS/KBANK1554I01/v1", "KBANK1554I01");
    private static final Logger LOG = Logger.getLogger(KBANK1554I01Soap_KBANK1554I01SoapPort_Client.class.getName());
    
    private KBANK1554I01Soap_KBANK1554I01SoapPort_Client() {
    }
    
    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = KBANK1554I01.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOG.info(e.getMessage());
            }
        }
      
        KBANK1554I01 ss = new KBANK1554I01(wsdlURL, SERVICE_NAME);
        KBANK1554I01Soap port = ss.getKBANK1554I01SoapPort();  
        
        {
        LOG.info("Invoking doService...");
        com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoService.KBANK1554I01 _doService_kbank1554I01 = new com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoService.KBANK1554I01();
        com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoService.KBANK1554I01.KBankHeader _doService_kbank1554I01KBankHeader = new com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoService.KBANK1554I01.KBankHeader();
        _doService_kbank1554I01KBankHeader.setFuncNm("KBANK1554I01");
        _doService_kbank1554I01KBankHeader.setRqUID("RqUID1717616698");
        _doService_kbank1554I01KBankHeader.setRqDt(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-05-16T10:46:01.954+07:00"));
        _doService_kbank1554I01KBankHeader.setRqAppId("RqAppId2006462517");
        _doService_kbank1554I01KBankHeader.setUserId("UserId1637914760");
        _doService_kbank1554I01KBankHeader.setTerminalId("TerminalId-1265492891");
        javax.xml.bind.JAXBElement<java.lang.String> _doService_kbank1554I01KBankHeaderUserLangPref = null;
        _doService_kbank1554I01KBankHeader.setUserLangPref(_doService_kbank1554I01KBankHeaderUserLangPref);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_kbank1554I01KBankHeaderCorrID = null;
        _doService_kbank1554I01KBankHeader.setCorrID(_doService_kbank1554I01KBankHeaderCorrID);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_kbank1554I01KBankHeaderAuthUserId = null;
        _doService_kbank1554I01KBankHeader.setAuthUserId(_doService_kbank1554I01KBankHeaderAuthUserId);
        javax.xml.bind.JAXBElement<java.lang.Integer> _doService_kbank1554I01KBankHeaderAuthLevel = null;
        _doService_kbank1554I01KBankHeader.setAuthLevel(_doService_kbank1554I01KBankHeaderAuthLevel);
        _doService_kbank1554I01.setKBankHeader(_doService_kbank1554I01KBankHeader);
        com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoService.KBANK1554I01.CISAccount _doService_kbank1554I01CISAccount = new com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoService.KBANK1554I01.CISAccount();
        _doService_kbank1554I01CISAccount.setNum("Num33430473");
        _doService_kbank1554I01.setCISAccount(_doService_kbank1554I01CISAccount);
        com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response _doService__return = port.doService(_doService_kbank1554I01);
        LOG.info("doService.result=" + _doService__return);


        }

        System.exit(0);
    }

}
