package com.kasikornbank.eai.eaiws.kbank1554i01.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-16T10:46:01.989+07:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "KBANK1554I01", 
                  wsdlLocation = "classpath:xsd/KBANK1554I01.wsdl",
                  targetNamespace = "http://eai.kasikornbank.com/EAIWS/KBANK1554I01/v1") 
public class KBANK1554I01 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://eai.kasikornbank.com/EAIWS/KBANK1554I01/v1", "KBANK1554I01");
    public final static QName KBANK1554I01SoapPort = new QName("http://eai.kasikornbank.com/EAIWS/KBANK1554I01/v1", "KBANK1554I01SoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/LMS/EAIService/WebContent/WEB-INF/wsdl/KBANK1554I01.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(KBANK1554I01.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/LMS/EAIService/WebContent/WEB-INF/wsdl/KBANK1554I01.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public KBANK1554I01(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KBANK1554I01(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KBANK1554I01() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public KBANK1554I01(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public KBANK1554I01(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public KBANK1554I01(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns KBANK1554I01Soap
     */
    @WebEndpoint(name = "KBANK1554I01SoapPort")
    public KBANK1554I01Soap getKBANK1554I01SoapPort() {
        return super.getPort(KBANK1554I01SoapPort, KBANK1554I01Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KBANK1554I01Soap
     */
    @WebEndpoint(name = "KBANK1554I01SoapPort")
    public KBANK1554I01Soap getKBANK1554I01SoapPort(WebServiceFeature... features) {
        return super.getPort(KBANK1554I01SoapPort, KBANK1554I01Soap.class, features);
    }

}
