package com.kasikornbank.eai.eaiws.kbank1554i01.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-16T10:46:01.980+07:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://eai.kasikornbank.com/EAIWS/KBANK1554I01/v1", name = "KBANK1554I01Soap")
@XmlSeeAlso({ObjectFactory.class})
@FunctionalInterface
public interface KBANK1554I01Soap {

    @WebResult(name = "KBANK1554I01Response", targetNamespace = "http://eai.kasikornbank.com/EAIWS/KBANK1554I01/v1")
    @RequestWrapper(localName = "doService", targetNamespace = "http://eai.kasikornbank.com/EAIWS/KBANK1554I01/v1", className = "com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoService")
    @WebMethod
    @ResponseWrapper(localName = "doServiceResponse", targetNamespace = "http://eai.kasikornbank.com/EAIWS/KBANK1554I01/v1", className = "com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse")
    public com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoServiceResponse.KBANK1554I01Response doService(
        @WebParam(name = "KBANK1554I01", targetNamespace = "http://eai.kasikornbank.com/EAIWS/KBANK1554I01/v1")
        com.kasikornbank.eai.eaiws.kbank1554i01.v1.DoService.KBANK1554I01 kbank1554I01
    );
}
