package com.kbank.lms.soap.ws.service;


import javax.jws.WebService;
import javax.xml.ws.BindingType;

import org.springframework.beans.factory.annotation.Autowired;
import com.kbank.corp.lms.schema.lmsprofileservice.LMSProfileService;
import com.kbank.corp.umm.schema.companymanagement.CheckDeleteCompanyReqBase;
import com.kbank.corp.umm.schema.companymanagement.CheckDeleteCompanyResBase;
import com.kbank.corp.umm.schema.companymanagement.CreateCompanyReqBase;
import com.kbank.corp.umm.schema.companymanagement.CreateCompanyResBase;
import com.kbank.corp.umm.schema.companymanagement.DeleteCompanyReqBase;
import com.kbank.corp.umm.schema.companymanagement.DeleteCompanyResBase;
import com.kbank.corp.umm.schema.companymanagement.ModifyCompanyReqBase;
import com.kbank.corp.umm.schema.companymanagement.ModifyCompanyResBase;
import com.kbank.corp.umm.schema.usermanagement.CheckDeleteUserReqBase;
import com.kbank.corp.umm.schema.usermanagement.CheckDeleteUserResBase;
import com.kbank.corp.umm.schema.usermanagement.CreateUserReqBase;
import com.kbank.corp.umm.schema.usermanagement.CreateUserResBase;
import com.kbank.corp.umm.schema.usermanagement.DeleteUserReqBase;
import com.kbank.corp.umm.schema.usermanagement.DeleteUserResBase;
import com.kbank.corp.umm.schema.usermanagement.ModifyUserReqBase;
import com.kbank.corp.umm.schema.usermanagement.ModifyUserResBase;


/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.3-06/19/2008
 * 07:03 PM(bt) Generated source version: 2.1
 * 
 */

@WebService(
		endpointInterface = "com.kbank.corp.lms.schema.lmsprofileservice.LMSProfileService",
		serviceName = "LMSProfileService",
		portName = "LMSProfileServicePort",
		wsdlLocation = "/xsd/LMSProfileService.wsdl",
		targetNamespace = "http://lms.corp.kbank.com/schema/LMSProfileService" 
		)
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class LMSProfileServiceImpl  implements LMSProfileService {
	
	@Autowired
	private CorporationManagementService corporationManagementService;
	
	@Autowired
	private UserManagementService userManagementService;
	
	/**
	 * 
	 * @param input
	 * @return returns
	 *         com.kbank.corp.umm.schema.usermanagement.CreateUserResBase
	 */

	@Override
	public CreateUserResBase createUser(CreateUserReqBase input) {
		return userManagementService.createUser(input);		
	}

	/**
	 * 
	 * @param input
	 * @return returns
	 *         com.kbank.corp.umm.schema.usermanagement.ModifyUserResBase
	 */
	@Override
	public ModifyUserResBase modifyUser(ModifyUserReqBase input) {
		return userManagementService.modifyUser(input);
	}

	/**
	 * 
	 * @param input
	 * @return returns
	 *         com.kbank.corp.umm.schema.usermanagement.DeleteUserResBase
	 */
	@Override
	public DeleteUserResBase deleteUser(DeleteUserReqBase input) {
		return userManagementService.deleteUser(input);
	}

	/**
	 * 
	 * @param input
	 * @return returns
	 *         com.kbank.corp.umm.schema.usermanagement.CheckDeleteUserResBase
	 */
	@Override
	public CheckDeleteUserResBase checkDeleteUser(CheckDeleteUserReqBase input) {
		return userManagementService.checkDeleteUser(input);
	}

	/**
	 * 
	 * @param input
	 * @return returns
	 *         com.kbank.corp.umm.schema.companymanagement.CreateCompanyResBase
	 */
	@Override
	public CreateCompanyResBase createCompany(CreateCompanyReqBase input) {
		return corporationManagementService.createCompany(input);
	}

	/**
	 * 
	 * @param input
	 * @return returns
	 *         com.kbank.corp.umm.schema.companymanagement.ModifyCompanyResBase
	 */
	@Override
	public ModifyCompanyResBase modifyCompany(ModifyCompanyReqBase input) {
		return corporationManagementService.modifyCompany(input);
	}

	/**
	 * 
	 * @param input
	 * @return returns
	 *         com.kbank.corp.umm.schema.companymanagement.DeleteCompanyResBase
	 */
	@Override
	public DeleteCompanyResBase deleteCompany(DeleteCompanyReqBase input) {
		return corporationManagementService.deleteCompany(input);
	}

	/**
	 * 
	 * @param input
	 * @return returns
	 *         com.kbank.corp.umm.schema.companymanagement.CheckDeleteCompanyResBase
	 */
	@Override
	public CheckDeleteCompanyResBase checkDeleteCompany( CheckDeleteCompanyReqBase input) {
		return corporationManagementService.checkDeleteCompany(input);
	}

}
