package com.kasikornbank.eai.eaiws.cis0367i01.v9;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-17T15:49:09.223+07:00
 * Generated source version: 3.1.11
 * 
 */
@WebService(targetNamespace = "http://eai.kasikornbank.com/EAIWS/CIS0367I01/v9", name = "CIS0367I01Soap")
@XmlSeeAlso({ObjectFactory.class})
@FunctionalInterface
public interface CIS0367I01Soap {

    @WebResult(name = "CIS0367I01Response", targetNamespace = "http://eai.kasikornbank.com/EAIWS/CIS0367I01/v9")
    @RequestWrapper(localName = "doService", targetNamespace = "http://eai.kasikornbank.com/EAIWS/CIS0367I01/v9", className = "com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService")
    @WebMethod
    @ResponseWrapper(localName = "doServiceResponse", targetNamespace = "http://eai.kasikornbank.com/EAIWS/CIS0367I01/v9", className = "com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse")
    public com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response doService(
        @WebParam(name = "CIS0367I01", targetNamespace = "http://eai.kasikornbank.com/EAIWS/CIS0367I01/v9")
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01 cis0367I01
    );
}
