package com.kasikornbank.eai.eaiws.cis0367i01.v9;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-17T15:49:09.231+07:00
 * Generated source version: 3.1.11
 * 
 */
@WebServiceClient(name = "CIS0367I01", 
                  wsdlLocation = "classpath:xsd/CIS0367I01.wsdl",
                  targetNamespace = "http://eai.kasikornbank.com/EAIWS/CIS0367I01/v9") 
public class CIS0367I01 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://eai.kasikornbank.com/EAIWS/CIS0367I01/v9", "CIS0367I01");
    public final static QName CIS0367I01SoapPort = new QName("http://eai.kasikornbank.com/EAIWS/CIS0367I01/v9", "CIS0367I01SoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/LMS/EAIService/src/main/resources/xsd/CIS0367I01.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CIS0367I01.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/LMS/EAIService/src/main/resources/xsd/CIS0367I01.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CIS0367I01(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CIS0367I01(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CIS0367I01() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public CIS0367I01(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CIS0367I01(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CIS0367I01(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns CIS0367I01Soap
     */
    @WebEndpoint(name = "CIS0367I01SoapPort")
    public CIS0367I01Soap getCIS0367I01SoapPort() {
        return super.getPort(CIS0367I01SoapPort, CIS0367I01Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CIS0367I01Soap
     */
    @WebEndpoint(name = "CIS0367I01SoapPort")
    public CIS0367I01Soap getCIS0367I01SoapPort(WebServiceFeature... features) {
        return super.getPort(CIS0367I01SoapPort, CIS0367I01Soap.class, features);
    }

}
