
package com.kasikornbank.eai.eaiws.cis0367i01.v9;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;

import com.kasikornbank.eai.eaiws.cbs1183i01.v2.CBS1183I01Soap_CBS1183I01SoapPort_Client;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-17T15:49:09.156+07:00
 * Generated source version: 3.1.11
 * 
 */
public final class CIS0367I01Soap_CIS0367I01SoapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://eai.kasikornbank.com/EAIWS/CIS0367I01/v9", "CIS0367I01");
    private static final Logger LOG = Logger.getLogger(CBS1183I01Soap_CBS1183I01SoapPort_Client.class.getName());
    
    private CIS0367I01Soap_CIS0367I01SoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CIS0367I01.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
            	LOG.info(e.getMessage());
            }
        }
      
        CIS0367I01 ss = new CIS0367I01(wsdlURL, SERVICE_NAME);
        CIS0367I01Soap port = ss.getCIS0367I01SoapPort();  
        
        {
        LOG.info("Invoking doService...");
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01 _doService_cis0367I01 = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01();
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.EAIHeader _doService_cis0367I01EAIHeader = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.EAIHeader();
        _doService_cis0367I01EAIHeader.setServiceId("ServiceId-1676861157");
        _doService_cis0367I01EAIHeader.setBeginTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-05-17T15:49:09.195+07:00"));
        javax.xml.bind.JAXBElement<javax.xml.datatype.XMLGregorianCalendar> _doService_cis0367I01EAIHeaderEndTimestamp = null;
        _doService_cis0367I01EAIHeader.setEndTimestamp(_doService_cis0367I01EAIHeaderEndTimestamp);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01EAIHeaderTransactionId = null;
        _doService_cis0367I01EAIHeader.setTransactionId(_doService_cis0367I01EAIHeaderTransactionId);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01EAIHeaderSourceTransactionId = null;
        _doService_cis0367I01EAIHeader.setSourceTransactionId(_doService_cis0367I01EAIHeaderSourceTransactionId);
        _doService_cis0367I01EAIHeader.setSourceSystem("SourceSystem1269770417");
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01EAIHeaderUserId = null;
        _doService_cis0367I01EAIHeader.setUserId(_doService_cis0367I01EAIHeaderUserId);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01EAIHeaderPassword = null;
        _doService_cis0367I01EAIHeader.setPassword(_doService_cis0367I01EAIHeaderPassword);
        javax.xml.bind.JAXBElement<java.lang.Integer> _doService_cis0367I01EAIHeaderStatus = null;
        _doService_cis0367I01EAIHeader.setStatus(_doService_cis0367I01EAIHeaderStatus);
        javax.xml.bind.JAXBElement<java.lang.Integer> _doService_cis0367I01EAIHeaderReasonCode = null;
        _doService_cis0367I01EAIHeader.setReasonCode(_doService_cis0367I01EAIHeaderReasonCode);
        _doService_cis0367I01.setEAIHeader(_doService_cis0367I01EAIHeader);
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer _doService_cis0367I01CISCustomer = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer();
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.AcctsObj _doService_cis0367I01CISCustomerAcctsObj = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.AcctsObj();
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.AcctsObj.AcctsVect _doService_cis0367I01CISCustomerAcctsObjAcctsVect = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.AcctsObj.AcctsVect();
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.AcctsObj.AcctsVect.CISAccount _doService_cis0367I01CISCustomerAcctsObjAcctsVectCISAccount = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.AcctsObj.AcctsVect.CISAccount();
        _doService_cis0367I01CISCustomerAcctsObjAcctsVectCISAccount.setNum("Num-88455024");
        _doService_cis0367I01CISCustomerAcctsObjAcctsVect.setCISAccount(_doService_cis0367I01CISCustomerAcctsObjAcctsVectCISAccount);
        _doService_cis0367I01CISCustomerAcctsObj.setAcctsVect(_doService_cis0367I01CISCustomerAcctsObjAcctsVect);
        _doService_cis0367I01CISCustomer.setAcctsObj(_doService_cis0367I01CISCustomerAcctsObj);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISCustomerBrNo = null;
        _doService_cis0367I01CISCustomer.setBrNo(_doService_cis0367I01CISCustomerBrNo);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISCustomerDocNum = null;
        _doService_cis0367I01CISCustomer.setDocNum(_doService_cis0367I01CISCustomerDocNum);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISCustomerDocTypeCode = null;
        _doService_cis0367I01CISCustomer.setDocTypeCode(_doService_cis0367I01CISCustomerDocTypeCode);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISCustomerNum = null;
        _doService_cis0367I01CISCustomer.setNum(_doService_cis0367I01CISCustomerNum);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISCustomerProdCode = null;
        _doService_cis0367I01CISCustomer.setProdCode(_doService_cis0367I01CISCustomerProdCode);
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.RMTeamObj _doService_cis0367I01CISCustomerRMTeamObj = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.RMTeamObj();
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.RMTeamObj.RMEmpObj _doService_cis0367I01CISCustomerRMTeamObjRMEmpObj = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.RMTeamObj.RMEmpObj();
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISCustomerRMTeamObjRMEmpObjEmpNum = null;
        _doService_cis0367I01CISCustomerRMTeamObjRMEmpObj.setEmpNum(_doService_cis0367I01CISCustomerRMTeamObjRMEmpObjEmpNum);
        _doService_cis0367I01CISCustomerRMTeamObj.setRMEmpObj(_doService_cis0367I01CISCustomerRMTeamObjRMEmpObj);
        _doService_cis0367I01CISCustomer.setRMTeamObj(_doService_cis0367I01CISCustomerRMTeamObj);
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.ServicesObj _doService_cis0367I01CISCustomerServicesObj = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.ServicesObj();
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.ServicesObj.ServicesVect _doService_cis0367I01CISCustomerServicesObjServicesVect = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.ServicesObj.ServicesVect();
        java.util.List<com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.ServicesObj.ServicesVect.CISEntities> _doService_cis0367I01CISCustomerServicesObjServicesVectCISEntities = new java.util.ArrayList<com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISCustomer.ServicesObj.ServicesVect.CISEntities>();
        _doService_cis0367I01CISCustomerServicesObjServicesVect.getCISEntities().addAll(_doService_cis0367I01CISCustomerServicesObjServicesVectCISEntities);
        _doService_cis0367I01CISCustomerServicesObj.setServicesVect(_doService_cis0367I01CISCustomerServicesObjServicesVect);
        _doService_cis0367I01CISCustomer.setServicesObj(_doService_cis0367I01CISCustomerServicesObj);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISCustomerThFstName = null;
        _doService_cis0367I01CISCustomer.setThFstName(_doService_cis0367I01CISCustomerThFstName);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISCustomerThLstName = null;
        _doService_cis0367I01CISCustomer.setThLstName(_doService_cis0367I01CISCustomerThLstName);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISCustomerTypeCode = null;
        _doService_cis0367I01CISCustomer.setTypeCode(_doService_cis0367I01CISCustomerTypeCode);
        _doService_cis0367I01.setCISCustomer(_doService_cis0367I01CISCustomer);
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISNavCntrl _doService_cis0367I01CISNavCntrl = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISNavCntrl();
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISNavCntrlDirCode = null;
        _doService_cis0367I01CISNavCntrl.setDirCode(_doService_cis0367I01CISNavCntrlDirCode);
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISNavCntrl.FstKeyNum _doService_cis0367I01CISNavCntrlFstKeyNum = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISNavCntrl.FstKeyNum();
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISNavCntrlFstKeyNumCustNum = null;
        _doService_cis0367I01CISNavCntrlFstKeyNum.setCustNum(_doService_cis0367I01CISNavCntrlFstKeyNumCustNum);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISNavCntrlFstKeyNumThFstName = null;
        _doService_cis0367I01CISNavCntrlFstKeyNum.setThFstName(_doService_cis0367I01CISNavCntrlFstKeyNumThFstName);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISNavCntrlFstKeyNumThLstName = null;
        _doService_cis0367I01CISNavCntrlFstKeyNum.setThLstName(_doService_cis0367I01CISNavCntrlFstKeyNumThLstName);
        _doService_cis0367I01CISNavCntrl.setFstKeyNum(_doService_cis0367I01CISNavCntrlFstKeyNum);
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISNavCntrl.LstKeyNum _doService_cis0367I01CISNavCntrlLstKeyNum = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01.CISNavCntrl.LstKeyNum();
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISNavCntrlLstKeyNumCustNum = null;
        _doService_cis0367I01CISNavCntrlLstKeyNum.setCustNum(_doService_cis0367I01CISNavCntrlLstKeyNumCustNum);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISNavCntrlLstKeyNumThFstName = null;
        _doService_cis0367I01CISNavCntrlLstKeyNum.setThFstName(_doService_cis0367I01CISNavCntrlLstKeyNumThFstName);
        javax.xml.bind.JAXBElement<java.lang.String> _doService_cis0367I01CISNavCntrlLstKeyNumThLstName = null;
        _doService_cis0367I01CISNavCntrlLstKeyNum.setThLstName(_doService_cis0367I01CISNavCntrlLstKeyNumThLstName);
        _doService_cis0367I01CISNavCntrl.setLstKeyNum(_doService_cis0367I01CISNavCntrlLstKeyNum);
        _doService_cis0367I01.setCISNavCntrl(_doService_cis0367I01CISNavCntrl);
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response _doService__return = port.doService(_doService_cis0367I01);
        LOG.info("doService.result=" + _doService__return);


        }

        System.exit(0);
    }

}
