
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.kasikornbank.eai.eaiws.cis0367i01.v9;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.1.11
 * 2017-05-17T15:49:09.205+07:00
 * Generated source version: 3.1.11
 * 
 */

@javax.jws.WebService(
                      serviceName = "CIS0367I01",
                      portName = "CIS0367I01SoapPort",
                      targetNamespace = "http://eai.kasikornbank.com/EAIWS/CIS0367I01/v9",
                      wsdlLocation = "classpath:xsd/CIS0367I01.wsdl",
                      endpointInterface = "com.kasikornbank.eai.eaiws.cis0367i01.v9.CIS0367I01Soap")
                      
public class CIS0367I01SoapPortImpl implements CIS0367I01Soap {

    private static final Logger LOG = Logger.getLogger(CIS0367I01SoapPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.kasikornbank.eai.eaiws.cis0367i01.v9.CIS0367I01Soap#doService(com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01 cis0367I01)*
     */
    
    public com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response doService(com.kasikornbank.eai.eaiws.cis0367i01.v9.DoService.CIS0367I01 cis0367I01) { 
        LOG.info("Executing operation doService");
        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response _return = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response();
        try {
	        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.EAIHeader _returnEAIHeader = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.EAIHeader();
	        _returnEAIHeader.setServiceId("ServiceId-1965449127");
	        _returnEAIHeader.setBeginTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-05-17T15:49:09.219+07:00"));
	        _returnEAIHeader.setEndTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-05-17T15:49:09.220+07:00"));
	        _returnEAIHeader.setTransactionId("TransactionId323865778");
	        _returnEAIHeader.setSourceTransactionId("SourceTransactionId-835257692");
	        _returnEAIHeader.setSourceSystem("SourceSystem-1170345047");
	        javax.xml.bind.JAXBElement<java.lang.String> _returnEAIHeaderUserId = null;
	        _returnEAIHeader.setUserId(_returnEAIHeaderUserId);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnEAIHeaderPassword = null;
	        _returnEAIHeader.setPassword(_returnEAIHeaderPassword);
	        _returnEAIHeader.setStatus(Integer.valueOf(-191249509));
	        _returnEAIHeader.setReasonCode(Integer.valueOf(-1209667138));
	        _returnEAIHeader.setReasonDesc("ReasonDesc1005451318");
	        _return.setEAIHeader(_returnEAIHeader);
	        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomer _returnCISCustomer = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomer();
	        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomer.AcctsObj _returnCISCustomerAcctsObj = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomer.AcctsObj();
	        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomer.AcctsObj.AcctsVect _returnCISCustomerAcctsObjAcctsVect = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomer.AcctsObj.AcctsVect();
	        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomer.AcctsObj.AcctsVect.CISAccount _returnCISCustomerAcctsObjAcctsVectCISAccount = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomer.AcctsObj.AcctsVect.CISAccount();
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCISCustomerAcctsObjAcctsVectCISAccountNum = null;
	        _returnCISCustomerAcctsObjAcctsVectCISAccount.setNum(_returnCISCustomerAcctsObjAcctsVectCISAccountNum);
	        _returnCISCustomerAcctsObjAcctsVect.setCISAccount(_returnCISCustomerAcctsObjAcctsVectCISAccount);
	        _returnCISCustomerAcctsObj.setAcctsVect(_returnCISCustomerAcctsObjAcctsVect);
	        _returnCISCustomer.setAcctsObj(_returnCISCustomerAcctsObj);
	        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomer.RMTeamObj _returnCISCustomerRMTeamObj = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomer.RMTeamObj();
	        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomer.RMTeamObj.RMEmpObj _returnCISCustomerRMTeamObjRMEmpObj = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomer.RMTeamObj.RMEmpObj();
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCISCustomerRMTeamObjRMEmpObjEmpNum = null;
	        _returnCISCustomerRMTeamObjRMEmpObj.setEmpNum(_returnCISCustomerRMTeamObjRMEmpObjEmpNum);
	        _returnCISCustomerRMTeamObj.setRMEmpObj(_returnCISCustomerRMTeamObjRMEmpObj);
	        _returnCISCustomer.setRMTeamObj(_returnCISCustomerRMTeamObj);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCISCustomerThFstName = null;
	        _returnCISCustomer.setThFstName(_returnCISCustomerThFstName);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCISCustomerThLstName = null;
	        _returnCISCustomer.setThLstName(_returnCISCustomerThLstName);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCISCustomerTypeCode = null;
	        _returnCISCustomer.setTypeCode(_returnCISCustomerTypeCode);
	        _return.setCISCustomer(_returnCISCustomer);
	        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomers _returnCISCustomers = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomers();
	        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomers.CISCustsVect _returnCISCustomersCISCustsVect = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomers.CISCustsVect();
	        java.util.List<com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomers.CISCustsVect.CISCustomer> _returnCISCustomersCISCustsVectCISCustomer = new java.util.ArrayList<com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISCustomers.CISCustsVect.CISCustomer>();
	        _returnCISCustomersCISCustsVect.getCISCustomer().addAll(_returnCISCustomersCISCustsVectCISCustomer);
	        _returnCISCustomers.setCISCustsVect(_returnCISCustomersCISCustsVect);
	        _returnCISCustomers.setTotCustCnt(Integer.valueOf(-282750935));
	        _return.setCISCustomers(_returnCISCustomers);
	        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISNavCntrl _returnCISNavCntrl = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISNavCntrl();
	        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISNavCntrl.FstKeyNum _returnCISNavCntrlFstKeyNum = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISNavCntrl.FstKeyNum();
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCISNavCntrlFstKeyNumCustNum = null;
	        _returnCISNavCntrlFstKeyNum.setCustNum(_returnCISNavCntrlFstKeyNumCustNum);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCISNavCntrlFstKeyNumTerminateFlag = null;
	        _returnCISNavCntrlFstKeyNum.setTerminateFlag(_returnCISNavCntrlFstKeyNumTerminateFlag);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCISNavCntrlFstKeyNumThFstName = null;
	        _returnCISNavCntrlFstKeyNum.setThFstName(_returnCISNavCntrlFstKeyNumThFstName);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCISNavCntrlFstKeyNumThLstName = null;
	        _returnCISNavCntrlFstKeyNum.setThLstName(_returnCISNavCntrlFstKeyNumThLstName);
	        _returnCISNavCntrl.setFstKeyNum(_returnCISNavCntrlFstKeyNum);
	        com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISNavCntrl.LstKeyNum _returnCISNavCntrlLstKeyNum = new com.kasikornbank.eai.eaiws.cis0367i01.v9.DoServiceResponse.CIS0367I01Response.CISNavCntrl.LstKeyNum();
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCISNavCntrlLstKeyNumCustNum = null;
	        _returnCISNavCntrlLstKeyNum.setCustNum(_returnCISNavCntrlLstKeyNumCustNum);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCISNavCntrlLstKeyNumTerminateFlag = null;
	        _returnCISNavCntrlLstKeyNum.setTerminateFlag(_returnCISNavCntrlLstKeyNumTerminateFlag);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCISNavCntrlLstKeyNumThFstName = null;
	        _returnCISNavCntrlLstKeyNum.setThFstName(_returnCISNavCntrlLstKeyNumThFstName);
	        javax.xml.bind.JAXBElement<java.lang.String> _returnCISNavCntrlLstKeyNumThLstName = null;
	        _returnCISNavCntrlLstKeyNum.setThLstName(_returnCISNavCntrlLstKeyNumThLstName);
	        _returnCISNavCntrl.setLstKeyNum(_returnCISNavCntrlLstKeyNum);
	        _return.setCISNavCntrl(_returnCISNavCntrl);
        } catch(Exception e){
        	LOG.info(e.getMessage());
        }
        return _return;
    }

}
